/**
更新数据库原生的sql
标注 作者/日期/版本/涉及功能
*/


--version 1.0
--author zhaoy
--date 2020-07-10 10:30:09
--demo演示
--update [table] set [column_name] where 1=1;


ALTER TABLE `c_customer_info`
ADD COLUMN `CITY`  varchar(30) NULL COMMENT '所在城市' AFTER `BIRTHDAY`;

ALTER TABLE `c_customer_info`
ADD COLUMN `REMARK`  varchar(200) NULL COMMENT '备注' AFTER `USER_BALANCE`;

ALTER TABLE `c_customer_info`
MODIFY COLUMN `CUSTOMER_INF_ID`  bigint NOT NULL AUTO_INCREMENT COMMENT '消费者信息详情主键ID' FIRST ;
ALTER TABLE `c_customer_info`
MODIFY COLUMN `CUSTOMER_ID`  varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '消费者主键ID' AFTER `CUSTOMER_INF_ID`;
ALTER TABLE `c_point_log`
MODIFY COLUMN `CUSTOMER_ID`  varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '消费者主键ID' AFTER `POINT_ID`;
ALTER TABLE `c_login_log`
MODIFY COLUMN `CUSTOMER_ID`  varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '消费者ID' AFTER `LOGIN_ID`;
ALTER TABLE `c_login`
MODIFY COLUMN `CUSTOMER_ID`  varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '客户主键ID' FIRST ;
ALTER TABLE `c_consignee`
MODIFY COLUMN `CUSTOMER_ID`  varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '消费者主键ID' AFTER `CUSTOMER_ADDR_ID`;
ALTER TABLE `c_collect`
MODIFY COLUMN `GOODS_ID`  varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '商品主键ID' AFTER `COLLECT_ID`,
MODIFY COLUMN `BUSINESS_ID`  varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '店铺主键ID' AFTER `GOODS_ID`,
ADD COLUMN `CUSTOMER_ID`  varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '消费者ID' AFTER `COLLECT_ID`;
ALTER TABLE `c_balance_log`
MODIFY COLUMN `CUSTOMER_ID`  varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '用户ID' AFTER `BALANCE_ID`;
ALTER TABLE `c_customer_info`
MODIFY COLUMN `IDENTY_CARD_TYPE`  integer(1) NULL COMMENT '证件类型：1 身份证，2 军官证，3 护照' AFTER `REAL_NAME`;

ALTER TABLE `c_customer_info`
ADD COLUMN `IS_DEL`  int NULL DEFAULT 0 COMMENT '是否删除 0否 1是' AFTER `REGISTER_TIME`;

ALTER TABLE `g_goods_param`
CHANGE COLUMN `PACKAGE` `PACKAGETYPE`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '包装' AFTER `COLOR`;

ALTER TABLE `g_goods_param`
MODIFY COLUMN `PROMOTE_START_DATE`  datetime NULL DEFAULT NULL COMMENT '促销开始时间' AFTER `PROMOTE_PRICE`,
MODIFY COLUMN `PROMOTE_END_DATE`  datetime NULL DEFAULT NULL COMMENT '促销结束时间' AFTER `PROMOTE_START_DATE`,
MODIFY COLUMN `IS_ONSALE`  int NULL DEFAULT 1 COMMENT '是否开售 1是 0否' AFTER `COUPON_SN`,
ADD COLUMN `COST_PRICE`  int NULL COMMENT '成本价' AFTER `SHOP_PRICE`,
ADD COLUMN `ID_DEL`  int NULL DEFAULT 0 COMMENT '是否删除 0否 1是' AFTER `COUPON_SN`,
ADD COLUMN `SORT_ORL`  int NULL DEFAULT NULL COMMENT '商品排序值' AFTER `SHIP_FEE`,
ADD COLUMN `IS_COMMENT`  int NULL DEFAULT 0 COMMENT '是否允许评论 0否 1是' AFTER `IS_ONSALE`,
ADD COLUMN `GOODS_TITLE`  varchar(200) NULL COMMENT '商品的简略标题' AFTER `GOODS_NAME`,
ADD COLUMN `SOURCE_SUPPLIER`  varchar(150) NULL COMMENT '原料产地' AFTER `SOURCE_ADDR`;


---------version 2020-08-11 10:13:40 zhaoy---------------
CREATE TABLE `SYS_CITY` (
`CITY_ID`  int NOT NULL AUTO_INCREMENT COMMENT '主键ID' ,
`CITY_CODE`  varchar(40) NULL COMMENT '城市code' ,
`CITY_NAME`  varchar(30) NULL COMMENT '城市名' ,
PRIMARY KEY (`CITY_ID`)
)
;


ALTER TABLE `g_goods`
CHANGE COLUMN `BUSINESS_ID` `BUSINESS_SN`  varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '所属店铺ID' AFTER `CATY_SN`;

ALTER TABLE `g_business`
CHANGE COLUMN `BUSINESS_CODE` `BUSINESS_SN`  varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '店铺代码' AFTER `BUSINESS_NAME`;


---------version 2020-08-12 11:13:40 zhaoy---------------

ALTER TABLE `g_goods_brand`
ADD COLUMN `BRAND_TYPE`  int NULL COMMENT '品牌类型' AFTER `BRAND_DESC`,
ADD COLUMN `CREATE_TIME`  datetime NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '商品录入时间' AFTER `IS_SHOW`,
ADD COLUMN `CREATE_BY`  varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '创建者' AFTER `CREATE_TIME`,
ADD COLUMN `UPDATE_TIME`  datetime NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '商品更新时间' AFTER `CREATE_BY`,
ADD COLUMN `UPDATE_BY`  varchar(30) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '更新者' AFTER `UPDATE_TIME`;

---------version 2020-08-18 18:13:40 zhaoy---------------

ALTER TABLE `g_goods_param`
MODIFY COLUMN `GIVE_INTEGRAL`  int NULL DEFAULT '-1' COMMENT '购买该商品时每笔成功交易赠送的积分数量' AFTER `SELLER_NOTE`,
ADD COLUMN `EXTENDS_PARAM`  text NULL COMMENT '自定义扩展属性' AFTER `GIVE_INTEGRAL`;

ALTER TABLE `g_goods_param`
CHANGE COLUMN `PACKAGETYPE` `PACKAGE_TYPE`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '包装' AFTER `COLOR`;

ALTER TABLE `g_goods_param`
CHANGE COLUMN `IS_ALONESALE` `IS_ALONE_SALE`  tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否能单独销售，1，是；0，否；如果不能单独销售，则只能作为某商品的配件或者赠品销售' AFTER `CLICK_COUNT`;

ALTER TABLE `c_level_info`
ADD COLUMN `LEVEL_STATUS`  tinyint(1) NULL DEFAULT 1 COMMENT '是否有效 0，无效 1有效' AFTER `MAX_POINT`,
ADD COLUMN `MODIFIED_TIME`  datetime NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间' AFTER `LEVEL_STATUS`;

ALTER TABLE `sys_menu`
ADD COLUMN `REMARK`  varchar(150) NULL COMMENT '菜单备注' AFTER `ORDER_NUM`;
ALTER TABLE `sys_user`
ADD COLUMN `REMARK`  varchar(150) NULL COMMENT '账号备注' AFTER `DEPT_NAME`;

alter table sys_user auto_increment=0;
alter table sys_role_menu auto_increment=0;
alter table sys_role auto_increment=0;
alter table sys_user_role auto_increment=0;
alter table sys_menu auto_increment=0;