package com.goktech.olala.server.pojo.sys;

import java.util.Date;

public class SysDict {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.id
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.value
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.keyword
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.up_id
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    private Integer upId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.dic_type
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    private String dicType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.status
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.operator_id
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    private String operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.operator_name
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    private String operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dict.create_time
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.id
     *
     * @return the value of sys_dict.id
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.id
     *
     * @param id the value for sys_dict.id
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.value
     *
     * @return the value of sys_dict.value
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.value
     *
     * @param value the value for sys_dict.value
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.keyword
     *
     * @return the value of sys_dict.keyword
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.keyword
     *
     * @param keyword the value for sys_dict.keyword
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.up_id
     *
     * @return the value of sys_dict.up_id
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public Integer getUpId() {
        return upId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.up_id
     *
     * @param upId the value for sys_dict.up_id
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public void setUpId(Integer upId) {
        this.upId = upId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.dic_type
     *
     * @return the value of sys_dict.dic_type
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public String getDicType() {
        return dicType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.dic_type
     *
     * @param dicType the value for sys_dict.dic_type
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public void setDicType(String dicType) {
        this.dicType = dicType == null ? null : dicType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.status
     *
     * @return the value of sys_dict.status
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.status
     *
     * @param status the value for sys_dict.status
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.operator_id
     *
     * @return the value of sys_dict.operator_id
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.operator_id
     *
     * @param operatorId the value for sys_dict.operator_id
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId == null ? null : operatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.operator_name
     *
     * @return the value of sys_dict.operator_name
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.operator_name
     *
     * @param operatorName the value for sys_dict.operator_name
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dict.create_time
     *
     * @return the value of sys_dict.create_time
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dict.create_time
     *
     * @param createTime the value for sys_dict.create_time
     *
     * @mbg.generated Tue Jul 07 16:57:55 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}